version: "3"
services:
  container1:
    image: container1:0.0.1
    container_name: container1
    networks:
      - app-network
    ports:
      - "8191:8091"
      # - "8190:8090"

  container2:
    image: container2:0.0.1
    container_name: container2
    networks:
      - app-network
    # ports:
    #  - "8192:8090"

  postgres:
    image: postgres:15 # postgres version 15
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/pgdata15
    networks:
      - app-network
    ports:
      - "5532:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"

  redis:
    image: redis:7
    container_name: redisserver
    networks:
      - app-network
    ports:
      - "6479:6379"
    volumes:
      - "./redis_data:/data"

volumes:
  redis_data:


networks:
  app-network:
    driver: bridge
